// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Results-Driven Development"
          descriptions={[
            "Fluxcorp is a specialized web development agency focused on transforming outdated digital presence into high-performance revenue drivers for businesses with 10 to 250 employees.",
            "We bridge the gap between creative design and technical excellence. Our team works as a seamless extension of your organization, handling every detail from strategic planning to post-launch optimization.",
            "Our philosophy is simple: websites should be measurable assets. We align your business goals with sophisticated technical solutions to ensure every feature, interface, and interaction serves a conversion purpose.",
          ]}
          primaryButton={{
            text: "Learn About Our Process",
            href: "#services",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
