// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Common Questions"
          title="Everything You Need to Know"
          description="Clear answers about how we partner with your business."
          items={[
            {
              question: "What is your typical project timeline?",
              answer: "Projects typically range from 4-8 weeks depending on scope, including strategy, development, and launch phases.",
            },
            {
              question: "Do you provide post-launch support?",
              answer: "Absolutely. We offer ongoing maintenance and growth-driven optimization packages for all our clients.",
            },
            {
              question: "Are your solutions scalable for the future?",
              answer: "Yes. We build all our platforms with scalability as a core architectural requirement.",
            },
            {
              question: "How do we measure project ROI?",
              answer: "We track key metrics including conversion rates, site performance, user engagement, and qualified lead generation.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
