// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesTaggedCards from '@/components/sections/features/FeaturesTaggedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesTaggedCards
          tag="Core Competencies"
          title="Comprehensive Web Services"
          description="Custom solutions tailored to your unique market challenges."
          items={[
            {
              tag: "Strategy",
              title: "Strategic Roadmap",
              description: "Defining your digital direction for maximum impact.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/be-change-inspired-active-thunder-website_53876-124706.jpg",
            },
            {
              tag: "Development",
              title: "Precision Engineering",
              description: "Fast, secure, and scalable web platforms.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/representations-user-experience-interface-design_23-2150038907.jpg",
            },
            {
              tag: "Infrastructure",
              title: "Scalable Hosting",
              description: "High-performance foundations for any workload.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/programmers-coding-laptop-using-artificial-intelligence-server-farm_482257-125015.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
