// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardTiltedCarousel from '@/components/sections/hero/HeroBillboardTiltedCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardTiltedCarousel
          tag="Your Digital Growth Partner"
          title="Custom Websites That Convert Visitors Into Customers"
          description="Fluxcorp builds fast, beautiful, results-driven websites designed for your business growth. From strategy to launch, we handle the complexity so you can focus on what matters."
          primaryButton={{
            text: "Start Your Project Today",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View Our Work",
            href: "#services",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/person-having-conversation-with-ai-virtual-assistant-producing-clips_482257-127292.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/multiethnic-group-coworkers-analyzing-business-charts-infographics-data-laptop-software-people-doing-teamwork-collaboration-create-paper-reviews-professional-report-close-up_482257-48646.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/technology-network-background-connection-cyber-space-ai-generative_123827-24187.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/three-black-ducks_23-2147680069.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/database-designer-writing-code-using-laptop-with-green-screen-chroma-key-mockup-sitting-desk-busy-developers-agency-programer-looking-multiple-screens-with-programming-language_482257-41854.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/keyboard-social-business-young-person_1150-1012.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
