// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
          tag="Measurable Impact"
          title="Proven Business ROI"
          description="We measure success in revenue, performance, and user satisfaction."
          metrics={[
            {
              value: "150%",
              title: "Avg Conversion Lift",
              description: "Real-world gains for our B2B partners.",
              imageSrc: "http://img.b2bpic.net/free-photo/birth-rate-fertility-concept_23-2148760991.jpg",
            },
            {
              value: "98%",
              title: "Client Retention",
              description: "Dedicated long-term support relationships.",
              imageSrc: "http://img.b2bpic.net/free-photo/internet-speed-test-software-concept_53876-120119.jpg",
            },
            {
              value: "<1s",
              title: "Load Speed",
              description: "Optimized performance for engagement.",
              imageSrc: "http://img.b2bpic.net/free-photo/alarm-clock-laptop-against-pink-background_23-2147943377.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
