// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesRevealCardsBento
          tag="Service Catalog"
          title="Everything Your Business Needs"
          description="From custom portals to growth engines, we build it all."
          items={[
            {
              title: "eCommerce Portals",
              description: "Secure shops with optimized checkouts.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/employee-looking-business-analytics_482257-115272.jpg",
            },
            {
              title: "CRM Integrations",
              description: "Syncing business data for efficiency.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/thumbs-up-network-circuit-board-link-connection-technology_1379-883.jpg",
            },
            {
              title: "UX Research",
              description: "Insights that drive conversion rates.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/female-web-designer-with-papers-notes-office_23-2149749911.jpg",
            },
            {
              title: "Brand Identity",
              description: "Unique digital presence design.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-measuring-tools-desk_23-2150440915.jpg",
            },
            {
              title: "SEO Engines",
              description: "Advanced visibility strategies.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/shoulder-view-african-american-startup-employee-looking-laptop-screen-with-business-analytics-charts-sitting-desk-close-focus-portable-computer-display-with-sales-results_482257-38698.jpg",
            },
            {
              title: "API Bridging",
              description: "Custom software integrations.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/technician-using-mockup-mobile-phone-data-center_482257-124694.jpg",
            },
            {
              title: "Performance Tuning",
              description: "Maximum load speed engineering.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/employee-uses-phone-app-with-greenscreen_482257-81843.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
