// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social-proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialProofSection(): React.JSX.Element {
  return (
    <div id="social-proof" data-section="social-proof">
        <SectionErrorBoundary name="social-proof">
              <SocialProofMarquee
          tag="Trusted by Leaders"
          title="Our Network of Growth Partners"
          description="We work with forward-thinking brands across various industries to drive digital success."
          names={[
            "InnovateTech",
            "GrowthStream",
            "ApexDesign",
            "GlobalShift",
            "BlueSkySoft",
            "NexGenBiz",
            "DigitalBridge",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
