// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Client Success"
          title="Trusted by Growing Businesses"
          description="Hear what our partners have to say about the Fluxcorp experience."
          testimonials={[
            {
              name: "Sarah Miller",
              role: "CEO",
              quote: "Fluxcorp transformed our digital presence. We saw immediate ROI after launch.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-mature-male-lawyer-with-laptop-wooden-table-courtroom_23-2147898629.jpg",
            },
            {
              name: "David Chen",
              role: "Marketing Manager",
              quote: "The team’s professionalism is unmatched. Fast, reliable, and expert-level.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-handsome-smiling-stylish-businessman-dark-background_613910-15034.jpg",
            },
            {
              name: "Elena Rodriguez",
              role: "VP Operations",
              quote: "They don't just build websites; they build business growth engines.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-confident-businessman-dressed-elegant-suit-shows-gesture-cool-while-standing-outdoors-against-cityscape-background_613910-4120.jpg",
            },
            {
              name: "Marcus Thorne",
              role: "Founder",
              quote: "Fluxcorp made the complexity of our transition seem simple. Highly recommend.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-man-black-suit_23-2148401442.jpg",
            },
            {
              name: "Jennifer Wu",
              role: "Product Director",
              quote: "Exceptional development speed and communication. Our project went off without a hitch.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-businessman-making-hand-gesture-with-cup-coffee-laptop-desk_23-2147955285.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
